#    $$$$$$$$\ $$\   $$\ $$\   $$\  $$$$$$\  $$\   $$\  $$$$$$\  $$$$$$$$\ $$$$$$$\
#    $$  _____|$$$\  $$ |$$ |  $$ |$$  __$$\ $$$\  $$ |$$  __$$\ $$  _____|$$  __$$\
#    $$ |      $$$$\ $$ |$$ |  $$ |$$ /  $$ |$$$$\ $$ |$$ /  \__|$$ |      $$ |  $$ |
#    $$$$$\    $$ $$\$$ |$$$$$$$$ |$$$$$$$$ |$$ $$\$$ |$$ |      $$$$$\    $$ |  $$ |
#    $$  __|   $$ \$$$$ |$$  __$$ |$$  __$$ |$$ \$$$$ |$$ |      $$  __|   $$ |  $$ |
#    $$ |      $$ |\$$$ |$$ |  $$ |$$ |  $$ |$$ |\$$$ |$$ |  $$\ $$ |      $$ |  $$ |
#    $$$$$$$$\ $$ | \$$ |$$ |  $$ |$$ |  $$ |$$ | \$$ |\$$$$$$  |$$$$$$$$\ $$$$$$$  |
#    \________|\__|  \__|\__|  \__|\__|  \__|\__|  \__| \______/ \________|\_______/
#    $$\      $$\ $$$$$$$$\  $$$$$$\ $$$$$$$$\ $$\   $$\ $$$$$$$$\ $$$$$$$\
#    $$ | $\  $$ |$$  _____|$$  __$$\\__$$  __|$$ |  $$ |$$  _____|$$  __$$\
#    $$ |$$$\ $$ |$$ |      $$ /  $$ |  $$ |   $$ |  $$ |$$ |      $$ |  $$ |
#    $$ $$ $$\$$ |$$$$$\    $$$$$$$$ |  $$ |   $$$$$$$$ |$$$$$\    $$$$$$$  |
#    $$$$  _$$$$ |$$  __|   $$  __$$ |  $$ |   $$  __$$ |$$  __|   $$  __$$<
#    $$$  / \$$$ |$$ |      $$ |  $$ |  $$ |   $$ |  $$ |$$ |      $$ |  $$ |
#    $$  /   \$$ |$$$$$$$$\ $$ |  $$ |  $$ |   $$ |  $$ |$$$$$$$$\ $$ |  $$ |
#    \__/     \__|\________|\__|  \__|  \__|   \__|  \__|\________|\__|  \__|

#---------------------------------------------------------------------------------------#

old weather message: Default Minecraft weather is disabled with Enhanced Weather running!



#---------------------------------------------------------------------------------------#
config version: 1 #DO NOT CHANGE THIS